[Basic]
;0-全功能 1-大圭 2-东莞
FactoryNameIndex=0
LightMinValue=150
traydata_sim=0
LineScanTestSpeed=220
take_mode=0
cy_delaytime=100
sim_tray_count=10
ScanBarcodeCount=3
trayBinCount=9
pos_left_safe=100
pos_right_safe=100
IsSaveDebugBMP=1
IsUseCalibrate=0
colFrist=5555
colSecond=10812
Chip_Reslution=0.0046
left_take_uppos=0
left_take_downpos=0
left_take_uptime=0
left_take_downtime=0
right_take_uppos=0
right_take_downpos=0
right_take_uptime=0
right_take_downtime=0
Offset_ModuleZ=0
Offset_LEAttract=0
Mirror1_Offset_Adj=0
Mirror2_Offset_Adj=0
LEPos=
AttractPos=
sMirror1PosList=
sMirror2PosList=
sMirror1PlanePosList=
sMirror2PlanePosList=
sMirror0PlanePosList=
sMirror0PlaneHeightPosList=
Mirror1CaliPos=
Mirror2CaliPos=
Mirror0CaliPos=
Mirror1PutPos=
Mirror2PutPos=
sMirror1JamedPosList=
sMirror2JamedPosList=
sMirrorTestDispensingPosList=
sMirrorTestDispensingReady=
ShadowPos=
ShadowPosUp=
sMirror1UVPosList=
sMirror2UVPosList=
DispensingInitialTime=3000
InitialDispensingPos=
sMirrorAdjDeepLength=0
sMirrorAdjDeep2Length=0
sMirrorPutAdjDeepLength=0
sMirrorPutAdjDeep2Length=0
sMirrorAdjBackLength=0
offsetCAM0CAM1=
offsetCAM2CAM1=
linescan_Xpos_start=200
linescan_Xpos_end=650
linescan_Ypos_start=10
linescan_Zpos_start=2
plc_loopCount=1
plc_quiverCount=2
IsAutoTestSavePicture=1
plc_mute_buzzer=0
pcForceStopPlc=0
feed_ypos=15.5
feed_zposlow=35
feed_zposhigh=47
take_ypos=991
take_zposlow=0
take_zposhigh=47
plc_testrun=1
cali_paras=0,120,5,-5,61,25,200,42000,50,300,50,300,150,300,1,0,0,0,0,0,100,2439.00;2572.00;26420.00;11159.00,
L1Path=D:\JETEAZY\LASER-MAIN_X1\Cali\zuizhongban20241006194253911.msr
L2Path=D:\JETEAZY\LASER-MAIN_X1\Cali\zuizhongban20241006194253911.msr
IsOnlyUseLeft=1
BoundaryValue=15000
LaserSharePath=D:\share\linescan
mark_rect= -10, -10, 500, 500
mark_org=    3999,    4723

；mark_rect=3794,4458, 500, 500
；mark_org=    3999,    4723

mark_thresholdvalue=150
IsOpenThread=1
IsOpenDrawNumber=1
GetImageDelayTime=20
LightDelayTime=500
IsOpenShowSize=0
ShowSizeValue=1
tcp_ip=127.0.0.1
tcp_port=33000
Cal_Bcx=-1.3
Cal_Bcy=0
Cal_Bca=0
IsOpenPrintFirst=0
DIRRES_X=0.0102
DIRRES_Y=0.0102
IsUseStandBoard=1
L3Path=D:\JETEAZY\LASER-MAIN_X1\Cali\20241105010424323.msr
L4Path=D:\JETEAZY\LASER-MAIN_X1\Cali\Laser.msr
IsSaveResultImage=1
IsUseFixedMark=0
ImageQuality=10
ResultImagePath=D:\01LaserImagePath
GC_Angle=5
LedControlCount=1
mLangIndex=0
AutoLogoutTime=0
Cal_BcxLB=0
Cal_BcyLB=0
Cal_BcaLB=0
IsForceInspect=1
DrawFontSize=10
DrawLineWidth=1
IsOpenUpload=0
CurrentLotName=111
IsOpenPlcMap=0
ImageResolution=0.0073
DelayImageTime=1000
IsSaveStripImage=0
IsSaveTestImage=0
tcp_handle_open=0
tcp_handle_ip=127.0.0.1
tcp_handle_port=33001
handle_delaytime=1500
FlyImageResolution=0.03
IsSaveDebugOrgBmp=1
IsResultShowChar=1
ImageResolutionX=0.0073
ImageResolutionY=0.00715
IsCheat=0
IsAutoDisableZoom=0
[FilePath]
CfgPath=
HWCPath=
[Other]
IsUseMeasureHeight=0
DispensingMsTime=50
[DX1]
sDispensingX1_1PosList=
sDispensingX1_2PosList=
GetPos1=0
GetPos2=0
PutPos1=0
PutPos2=0
UVWorkPos=0
UVWorkPos2=0
SafePosReady=
DispendingPosReady=
CheckVaccTime=10
LeftOutside=0
RightOutside=0
PosGetImage=0
IsBypassAOI=0
GetImageDelaytime=500
DispeningZDelaytime=2000
MidwayPosition1=
MidwayPosition2=
ChangeBeforePosition=
ChangeAfterPosition=
ChangeBeforeAfterAdjustPosition=0,0,0
[sql]
mysql_server_ip=localhost
mysql_server_port=3306
mysql_server_user=root
mysql_server_pwd=
mysql_server_db=db_2ds_sys
