[Camera Basic]
COUNT=2
[Camera 0]
Index=0
SerialNumber=DSXL17500000843
IsDebug=0
Rotate=0
;//HUARUI;DVP2;ITK;MIND
CameraType=DVP2
[Camera 1]
Index=1
SerialNumber=DSU024700000254
IsDebug=0
Rotate=0
;//HUARUI;DVP2;ITK;MIND
CameraType=DVP2
IsFly=1
[Camera 2]
Index=2
SerialNumber=BC24536AAK00022
IsDebug=1
Rotate=0
